import './globals.css'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl';
import Header from '@/components/Header';

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'vn' }];
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: {
    locale
  }
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {
  console.log('locale', locale)

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <div className='flex flex-col items-center justify-between p-24'>
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
